version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: theacquisitions-app
    env_file:
      - .env.production
    # environment:
    #   NODE_ENV: production
    ports:
      - '3000:3000'
    restart: unless-stopped
